# Generated by Django 5.0.3 on 2024-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_telegramexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='chart_income',
            field=models.FileField(blank=True, help_text='Файл с графиком доходов пользователя.', null=True, upload_to='chart_income/', verbose_name='График доходов'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chart',
            field=models.FileField(blank=True, help_text='Файл с графиком расходов пользователя.', null=True, upload_to='chart/', verbose_name='График расходов'),
        ),
    ]
